// src/components/ai/AIAnalysisSummary.jsx
import { Card, CardContent, Typography, Box, Stack, Chip, Grid, alpha } from "@mui/material";
import PsychologyRoundedIcon from "@mui/icons-material/PsychologyRounded";
import TrendingUpRoundedIcon from "@mui/icons-material/TrendingUpRounded";
import WarningAmberRoundedIcon from "@mui/icons-material/WarningAmberRounded";
import UpdateRoundedIcon from "@mui/icons-material/Update";

const AIAnalysisSummary = ({ summary }) => {
  if (!summary) return null;

  const adaptiveChipStyles = (colorKey) => ({
    width: "100%",
    height: 48,
    fontWeight: 700,
    fontSize: "0.825rem",
    textTransform: "uppercase",
    letterSpacing: "0.02em",
    borderRadius: "12px", 
    bgcolor: (theme) => alpha(theme.palette[colorKey].main, 0.06), 
    color: `${colorKey}.main`, 
    border: "1px solid",
    borderColor: (theme) => alpha(theme.palette[colorKey].main, 0.16),
    "& .MuiChip-icon": {
      color: `${colorKey}.main`,
      fontSize: 20
    },
    "& .MuiChip-label": {
      px: 1.5
    }
  });

  return (
    <Card
      elevation={0} 
      sx={{
        borderRadius: "24px", 
        border: "1px solid",
        borderColor: "divider", 
        bgcolor: "background.paper", 
        boxShadow: (theme) => theme.palette.mode === "dark" 
          ? "0 10px 30px rgba(0,0,0,0.3)" 
          : "0 10px 30px rgba(15, 23, 42, 0.01)"
      }}
    >
      <CardContent sx={{ p: 3, "&:last-child": { pb: 3 } }}>
        
        {/* ================= HEADER SECTOR ================= */}
        {/* ✅ FIXED: Transferred layout parameters directly into safe sx styling wrappers */}
        <Stack direction="row" spacing={2} sx={{ alignItems: "center", mb: 3.5 }}>
          <Box
            sx={{
              width: 44,
              height: 44,
              borderRadius: "10px", 
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              bgcolor: (theme) => alpha(theme.palette.primary.main, 0.08),
              color: "primary.main",
              border: "1px solid",
              borderColor: (theme) => alpha(theme.palette.primary.main, 0.15),
              flexShrink: 0
            }}
          >
            <PsychologyRoundedIcon sx={{ fontSize: 24 }} />
          </Box>
          
          <Box>
            <Typography variant="subtitle1" fontWeight={800} sx={{ color: "text.primary", letterSpacing: "-0.01em", lineHeight: 1.3 }}>
              AI Analysis Summary
            </Typography>
            <Typography variant="caption" sx={{ color: "text.secondary", fontWeight: 600 }}>
              Generated by Deadline Guardian AI
            </Typography>
          </Box>
        </Stack>

        {/* ================= COMPACT KPI METRICS MATRIX ROW ================= */}
        {/* ✅ FIXED: Stripped out legacy item layout properties */}
        <Grid container spacing={2}>
          <Grid xs={12} sm={6} md={3}>
            <Chip
              icon={<TrendingUpRoundedIcon />}
              label={`Score: ${summary.productivityScore ?? "--"}/100`}
              sx={adaptiveChipStyles("success")}
            />
          </Grid>

          <Grid xs={12} sm={6} md={3}>
            <Chip
              icon={<UpdateRoundedIcon />}
              label={`Updated: ${summary.updatedTasks ?? "--"}`}
              sx={adaptiveChipStyles("primary")}
            />
          </Grid>

          <Grid xs={12} sm={6} md={3}>
            <Chip
              icon={<WarningAmberRoundedIcon />}
              label={`Risks: ${summary.riskyTasks ?? "--"}`}
              sx={adaptiveChipStyles("warning")}
            />
          </Grid>

          <Grid xs={12} sm={6} md={3}>
            <Chip
              label={`${summary.workload ?? "--"} Hours Workload`}
              sx={adaptiveChipStyles("secondary")}
            />
          </Grid>
        </Grid>

        {/* ================= REFINED SUMMARY ANALYSIS BODY ================= */}
        <Box sx={{ mt: 4, pt: 3, borderTop: "1px solid", borderColor: "divider" }}>
          <Typography variant="subtitle2" fontWeight={800} sx={{ color: "text.primary", mb: 1, letterSpacing: "-0.01em" }}>
            Aggregate AI Insight
          </Typography>
          
          <Typography variant="body2" sx={{ color: "text.secondary", fontWeight: 500, lineHeight: 1.6 }}>
            {summary.summaryText || summary.summary || "No aggregate analytical summary metrics evaluated for this current operational lifecycle filter loop."}
          </Typography>
        </Box>
      </CardContent>
    </Card>
  );
};

export default AIAnalysisSummary;
