// src/components/ai/AIRecommendationCard.jsx
import {
  Card,
  CardContent,
  Typography,
  Stack,
  Box,
  alpha,
} from "@mui/material";

import TipsAndUpdatesRoundedIcon from "@mui/icons-material/TipsAndUpdatesRounded";
import CheckCircleRoundedIcon from "@mui/icons-material/CheckCircleRounded";

// ✅ FIXED: Changed parameter key from 'suggestions' to 'recommendations' to match parent property passing exactly
const AIRecommendationCard = ({ recommendations = [] }) => {
  const safeRecommendations = Array.isArray(recommendations) ? recommendations : [];

  return (
    <Card
      elevation={0}
      sx={{
        borderRadius: "24px", 
        border: "1px solid",
        borderColor: "divider", 
        bgcolor: "background.paper", 
        transition: "all 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        "&:hover": { 
          borderColor: (theme) => alpha(theme.palette.text.primary, 0.15),
          boxShadow: (theme) => theme.palette.mode === "dark" 
            ? "0 10px 30px rgba(0,0,0,0.3)" 
            : "0 10px 30px rgba(15, 23, 42, 0.02)" 
        },
      }}
    >
      <CardContent sx={{ p: 3, flexGrow: 1, display: "flex", flexDirection: "column", "&:last-child": { pb: 3 } }}>
        {/* ================= HEADER SECTOR ================= */}
        <Stack 
          spacing={1.5} 
          sx={{ 
            direction: "row",
            alignItems: "center",
            mb: 3 
          }}
        >
          <TipsAndUpdatesRoundedIcon sx={{ color: "warning.main", fontSize: 24 }} /> 
          <Typography variant="subtitle1" fontWeight={800} sx={{ color: "text.primary", letterSpacing: "-0.01em" }}>
            AI Recommendations
          </Typography>
        </Stack>

        {/* ✅ FIXED: Evaluates pre-sanitized recommendation datasets safely */}
        {safeRecommendations.length === 0 ? (
          <Typography sx={{ color: "text.secondary", fontWeight: 500, fontSize: "0.925rem", flexGrow: 1 }}>
            Run AI analysis to receive personalized recommendations.
          </Typography>
        ) : (
          <Stack spacing={2} sx={{ flexGrow: 1, flexDirection: "column" }}>
            {safeRecommendations.map((item, index) => (
              <Box 
                key={index} 
                sx={{ 
                  display: "flex", 
                  alignItems: "flex-start", 
                  gap: 1.5, 
                  p: 2, 
                  borderRadius: "14px", 
                  bgcolor: "background.default", 
                  border: "1px solid", 
                  borderColor: "divider" 
                }}
              >
                <CheckCircleRoundedIcon sx={{ color: "success.main", fontSize: 18, mt: 0.25, flexShrink: 0 }} />
                <Typography variant="body2" sx={{ fontWeight: 600, color: "text.primary", lineHeight: 1.5, width: "100%", textAlign: "left", wordBreak: "break-word" }}>
                  {item}
                </Typography>
              </Box>
            ))}
          </Stack>
        )}

        {safeRecommendations.length > 0 && (
          <Typography variant="caption" sx={{ display: "block", mt: 3, pt: 2, borderTop: "1px dashed", borderColor: "divider", color: "text.secondary", fontWeight: 500 }}>
            Recommendations are generated by Gemini AI based on your current tasks and productivity patterns.
          </Typography>
        )}
      </CardContent>
    </Card>
  );
};

export default AIRecommendationCard;
